### ISSUE TITLE
吹水

### ISSUE THREAD

**Issue by wherewhere** [zxbmmmmmmmmm/ITHome#1]
快点把Discussion打开，这样就能愉快的吹水了/滑稽

**Comment by mediaexplorer74** [comment]
> 快点把Discussion打开，这样就能愉快的吹水了/滑稽

Is zxbmmmmmmmmm your friend? =) Yea, switch Discussions tab on :)
And... add some Readme.md about this interesting project. What ITHome is, indeed? =)

**Comment by zxbmmmmmmmmm** [comment]
opened
